# Generated by Django 4.0.1 on 2022-01-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenetManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='participant_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('event_name', models.CharField(max_length=50)),
                ('registration_type', models.CharField(max_length=10)),
                ('no_of_people', models.CharField(default='1', max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='event_tbl',
            options={'verbose_name_plural': 'Events'},
        ),
        migrations.AlterField(
            model_name='event_tbl',
            name='deadLine',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event_tbl',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event_tbl',
            name='host_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='event_tbl',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event_tbl',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
